### ISSUE TITLE
KIX4OTRS and Znuny4OTRS Conflict

### ISSUE THREAD

**Issue by buts101** [znuny/Znuny4OTRS-Repo#13]
Trying to install Znuny4OTRS-Repo 5.0.2 package in the system having otrs5+itsm+kix4otrs return following error:

 Can't install/upgrade package, file var/httpd/htdocs/js/Core.UI.InputFields.js already used in package KIX4OTRS-8.0.0!

Backend ERROR: OTRS-CGI-86 Perl: 5.18.2 OS: linux Time: Thu Jul 14 12:12:13 2016 Message: Can't install/upgrade package, file var/httpd/htdocs/js/Core.UI.InputFields.js already used in package KIX4OTRS-8.0.0! RemoteAddress: 172.17.0.1 RequestURI: /otrs/index.pl Traceback (756): Module: Kernel::System::Package::_PackageFileCheck Line: 3264 Module: Kernel::System::Package::PackageInstall Line: 546 Module: Kernel::Modules::AdminPackageManager::_InstallHandling Line: 1925 Module: Kernel::Modules::AdminPackageManager::Run Line: 1278 Module: Kernel::System::Web::InterfaceAgent::Run Line: 1042 Module: ModPerl::ROOT::ModPerl::Registry::opt_otrs_bin_cgi_2dbin_index_2epl::handler Line: 53 Module: (eval) (v1.99) Line: 206 Module: ModPerl::RegistryCooker::run (v1.99) Line: 206 Module: ModPerl::RegistryCooker::default_handler (v1.99) Line: 172 Module: ModPerl::Registry::handler (v1.99) Line: 31 System information: OTRS 5.0.6

**Comment by thorsteneckel** [comment]
Hi @buts101 I'm sorry to tell you but our Znuny4OTRS extensions don't support any kix4otrs versions. kix4otrs itself is more a customization than an own framework which causes these conflicts with ours. I would gladly hear from you which features make kix4otrs so interesting for you to use it.

Maybe in future versions of our Znuny4OTRS-Repo the conflicting file will be removed since it only contains backported bugfixes for early OTRS5 versions. Nevertheless we won't give an official green light for using it with kix4otrs because of the basic changes made to the OTRS core.

**Comment by jenshavelberg** [comment]
:( any updates here? we need a solution for migration from otrs with kix.
thanks!

**Comment by thorsteneckel** [comment]
Hi @jenshavelberg - still no plans to make a compatible version with KIX - sorry.

**Comment by martini** [comment]
One more note. KIX is a OTRS fork. KIX will not be compatible to OTRS after some time. Then all Znuny4OTRS* packages will not work on KIX anymore.
